// TODO: Break this out into a real library
// <auto-generated>

namespace Warcraft.Core.Compression.Squish
{
    internal struct SourceBlock
    {
        public byte Start;
        public byte End;
        public byte Error;

        public SourceBlock(byte Start, byte End, byte Error)
        {
            this.Start = Start;
            this.End = End;
            this.Error = Error;
        }
    }
}
