//
//  DatabaseName.cs
//
//  Author:
//       Jarl Gullberg <jarl.gullberg@gmail.com>
//
//  Copyright (c) 2016 Jarl Gullberg
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

// ReSharper disable InconsistentNaming
#pragma warning disable 1591

namespace Warcraft.DBC
{
	/// <summary>
	/// Contains the names of all known databases, allowing for lookup and naming.
	/// </summary>
	public enum DatabaseName
	{
		AnimationData,
		AreaPOI,
		AreaTable,
		AreaTrigger,
		AttackAnimKits,
		AttackAnimTypes,
		AuctionHouse,
		BankBagSlotPrices,
		CameraShakes,
		Cfg_Categories,
		Cfg_Configs,
		CharacterCreateCameras,
		CharacterFacialHairStyles,
		CharBaseInfo,
		CharHairGeosets,
		CharHairTextures,
		CharSections,
		CharStartOutfit,
		CharVariations,
		ChatChannels,
		ChatProfanity,
		ChrClasses,
		ChrRaces,
		CinematicCamera,
		CinematicSequences,
		CreatureDisplayInfo,
		CreatureDisplayInfoExtra,
		CreatureFamily,
		CreatureModelData,
		CreatureSoundData,
		CreatureSpellData,
		CreatureType,
		DeathThudLookups,
		DurabilityCosts,
		DurabilityQuality,
		Emotes,
		EmotesTextData,
		EmotesText,
		EmotesTextSound,
		EnvironmentalDamage,
		Exhaustion,
		Faction,
		FactionGroup,
		FactionTemplate,
		FootprintTextures,
		FootstepTerrainLookup,
		GameObjectArtKit,
		GameObjectDisplayInfo,
		GameTips,
		GMSurveyCurrentSurvey,
		GMSurveyQuestions,
		GMSurveySurveys,
		GMTicketCategory,
		GroundEffectDoodad,
		GroundEffectTexture,
		HelmetGeosetVisData,
		ItemBagFamily,
		ItemClass,
		ItemDisplayInfo,
		ItemGroupSounds,
		ItemPetFood,
		ItemRandomProperties,
		ItemSet,
		ItemSubClass,
		ItemSubClassMask,
		ItemVisualEffects,
		ItemVisuals,
		Languages,
		LanguageWords,
		LFGDungeons,
		Light,
		LightFloatBand,
		LightIntBand,
		LightParams,
		LightSkybox,
		LiquidObject,
		LiquidType,
		LoadingScreens,
		LoadingScreenTaxiSplines,
		Lock,
		LockType,
		MailTemplate,
		Map,
		Material,
		NameGen,
		NamesProfanity,
		NamesReserved,
		NPCSounds,
		Package,
		PageTextMaterial,
		PaperDollItemFrame,
		PetLoyalty,
		PetPersonality,
		QuestInfo,
		QuestSort,
		Resistances,
		ServerMessages,
		SheatheSoundLookups,
		SkillCostsData,
		SkillLineAbility,
		SkillLineCategory,
		SkillLine,
		SkillRaceClassInfo,
		SkillTiers,
		SoundAmbience,
		SoundCharacterMacroLines,
		SoundEntries,
		SoundProviderPreferences,
		SoundSamplePreferences,
		SoundWaterType,
		SpamMessages,
		SpellAuraNames,
		SpellCastTimes,
		SpellCategory,
		SpellChainEffects,
		Spell,
		SpellDispelType,
		SpellDuration,
		SpellEffectCameraShakes,
		SpellEffectNames,
		SpellFocusObject,
		SpellIcon,
		SpellItemEnchantment,
		SpellMechanic,
		SpellRadius,
		SpellRange,
		SpellShapeshiftForm,
		SpellVisual,
		SpellVisualEffectName,
		SpellVisualKit,
		SpellVisualPrecastTransitions,
		StableSlotPrices,
		Startup_Strings,
		Stationery,
		StringLookups,
		Talent,
		TalentTab,
		TaxiNodes,
		TaxiPath,
		TaxiPathNode,
		TerrainType,
		TerrainTypeSounds,
		TransportAnimation,
		UISoundLookups,
		UnitBlood,
		UnitBloodLevels,
		VideoHardware,
		VocalUISounds,
		WeaponImpactSounds,
		WeaponSwingSounds2,
		WMOAreaTable,
		WorldMapArea,
		WorldMapContinent,
		WorldMapOverlay,
		WorldSafeLocs,
		WorldStateUI,
		WowError_Strings,
		ZoneAmbience,
		ZoneIntroMusicTable,
		ZoneMusic,
	}
}